



if True:
    # Sion
    # Yorick
    # Riven
    # Corki
    # Kled
    # Quinn
    # Tahm Kench
    # Lee Sin
    # swain
    #     mw-content
    #         ...
    #         tabber
    #             skillname
    #                 skill skill_x
    #             altskillname
    #                 skill skill_x
    #         ...
    # Lee Sin
    #     mw-content
    #         ...
    #         tabber
    #             skillname
    #                 skill skill_x
    #             altskillname
    #                 skill skill_x
    #         ^^^x3
    #         ...

    # elise
    #     mw-content
    #         ...
    #         tabber
    #             humanform
    #                 QWE
    #             altform
    #                 QWEalt
    #         ...
    # reksai
    #     mw-content
    #         tabber
    #             unburrowed
    #                 all
    #             alt
    #                 all
    #                 innate and R dont seem to change
    # nidalee
    #     mw-content
    #         ...
    #         tabber
    #             human
    #                 QWER
    #             alt
    #                 QWERalt
    #                 R is different
    # gnar
    #     mw-content
    #         ...
    #         tabber
    #             mini
    #                 QWE
    #             alt
    #                 QWEalt
    #         ...
    # jayce
    #     mw-content
    #         tabber
    #             hammer
    #                 all
    #             alt
    #                 all
    #                 innate dont seem to change




    # Corki
    # Elise
    # Gnar
    # Jayce
    # Kled
    # Lee Sin
    # Nidalee
    # Quinn
    # Rek'Sai
    # Riven
    # Sion
    # Swain
    # Tahm Kench
    # Yorick


    pass

    
def pretty(d):
    for key, value in d.items():
        print(str(key))
        for k,v in value.items():
            print('\t', k, ':', v)    


champ_names = ['Aatrox', 'Ahri', 'Akali', 'Alistar', 'Amumu', 'Anivia', 
               'Annie', 'Ashe', 'Aurelion_Sol', 'Azir', 'Bard', 'Blitzcrank', 
               'Brand', 'Braum', 'Caitlyn', 'Camille', 'Cassiopeia', 
               'Cho\'Gath', 'Corki', 'Darius', 'Diana', 'Dr._Mundo', 
               'Draven', 'Ekko', 'Elise', 'Evelynn', 'Ezreal', 'Fiddlesticks', 
               'Fiora', 'Fizz', 'Galio', 'Gangplank', 'Garen', 'Gnar', 'Gragas', 
               'Graves', 'Hecarim', 'Heimerdinger', 'Illaoi', 'Irelia', 'Ivern', 
               'Janna', 'Jarvan_IV', 'Jax', 'Jayce', 'Jhin', 'Jinx', 'Kai\'Sa', 
               'Kalista', 'Karma', 'Karthus', 'Kassadin', 'Katarina', 'Kayle', 
               'Kayn', 'Kennen', 'Kha\'Zix', 'Kindred', 'Kled', 'Kog\'Maw', 
               'LeBlanc', 'Lee_Sin', 'Leona', 'Lissandra', 'Lucian', 'Lulu', 
               'Lux', 'Malphite', 'Malzahar', 'Maokai', 'Master_Yi', 
               'Miss_Fortune', 'Mordekaiser', 'Morgana', 'Nami', 'Nasus', 
               'Nautilus', 'Nidalee', 'Nocturne', 'Nunu', 'Olaf', 'Orianna', 
               'Ornn', 'Pantheon', 'Poppy', 'Pyke', 'Quinn', 'Rakan', 'Rammus', 'Rek\'Sai', 
               'Renekton', 'Rengar', 'Riven', 'Rumble', 'Ryze', 'Sejuani', 
               'Shaco', 'Shen', 'Shyvana', 'Singed', 'Sion', 'Sivir', 'Skarner', 
               'Sona', 'Soraka', 'Swain', 'Syndra', 'Tahm_Kench', 'Taliyah', 
               'Talon', 'Taric', 'Teemo', 'Thresh', 'Tristana', 'Trundle', 
               'Tryndamere', 'Twisted_Fate', 'Twitch', 'Udyr', 'Urgot', 'Varus', 
               'Vayne', 'Veigar', 'Vel\'Koz', 'Vi', 'Viktor', 'Vladimir', 
               'Volibear', 'Warwick', 'Wukong', 'Xayah', 'Xerath', 'Xin_Zhao', 
               'Yasuo', 'Yorick', 'Zac', 'Zed', 'Ziggs', 'Zilean', 'Zoe', 'Zyra']

champ_names_word_only = ['Aatrox', 'Ahri', 'Akali', 'Alistar', 'Amumu', 'Anivia', 
               'Annie', 'Ashe', 'Aurelion_Sol', 'Azir', 'Bard', 'Blitzcrank', 
               'Brand', 'Braum', 'Caitlyn', 'Camille', 'Cassiopeia', 
               'ChoGath', 'Corki', 'Darius', 'Diana', 'Dr_Mundo', 
               'Draven', 'Ekko', 'Elise', 'Evelynn', 'Ezreal', 'Fiddlesticks', 
               'Fiora', 'Fizz', 'Galio', 'Gangplank', 'Garen', 'Gnar', 'Gragas', 
               'Graves', 'Hecarim', 'Heimerdinger', 'Illaoi', 'Irelia', 'Ivern', 
               'Janna', 'Jarvan_IV', 'Jax', 'Jayce', 'Jhin', 'Jinx', 'KaiSa', 
               'Kalista', 'Karma', 'Karthus', 'Kassadin', 'Katarina', 'Kayle', 
               'Kayn', 'Kennen', 'KhaZix', 'Kindred', 'Kled', 'KogMaw', 
               'LeBlanc', 'Lee_Sin', 'Leona', 'Lissandra', 'Lucian', 'Lulu', 
               'Lux', 'Malphite', 'Malzahar', 'Maokai', 'Master_Yi', 
               'Miss_Fortune', 'Mordekaiser', 'Morgana', 'Nami', 'Nasus', 
               'Nautilus', 'Nidalee', 'Nocturne', 'Nunu', 'Olaf', 'Orianna', 
               'Ornn', 'Pantheon', 'Poppy', 'Pyke', 'Quinn', 'Rakan', 'Rammus', 'RekSai', 
               'Renekton', 'Rengar', 'Riven', 'Rumble', 'Ryze', 'Sejuani', 
               'Shaco', 'Shen', 'Shyvana', 'Singed', 'Sion', 'Sivir', 'Skarner', 
               'Sona', 'Soraka', 'Swain', 'Syndra', 'Tahm_Kench', 'Taliyah', 
               'Talon', 'Taric', 'Teemo', 'Thresh', 'Tristana', 'Trundle', 
               'Tryndamere', 'Twisted_Fate', 'Twitch', 'Udyr', 'Urgot', 'Varus', 
               'Vayne', 'Veigar', 'VelKoz', 'Vi', 'Viktor', 'Vladimir', 
               'Volibear', 'Warwick', 'Wukong', 'Xayah', 'Xerath', 'Xin_Zhao', 
               'Yasuo', 'Yorick', 'Zac', 'Zed', 'Ziggs', 'Zilean', 'Zoe', 'Zyra']

champ_names_for_packages = ['aatrox', 'ahri', 'akali', 'alistar', 'amumu', 'anivia', 'annie', 'ashe', 'aurelion_sol', 'azir', 'bard', 'blitzcrank', 'brand', 'braum', 'caitlyn', 'camille', 'cassiopeia', 'chogath', 'corki', 'darius', 'diana', 'dr_mundo', 'draven', 'ekko', 'elise', 'evelynn', 'ezreal', 'fiddlesticks', 'fiora', 'fizz', 'galio', 'gangplank', 'garen', 'gnar', 'gragas', 'graves', 'hecarim', 'heimerdinger', 'illaoi', 'irelia', 'ivern', 'janna', 'jarvan_iv', 'jax', 'jayce', 'jhin', 'jinx', 'kaisa', 'kalista', 'karma', 'karthus', 'kassadin', 'katarina', 'kayle', 'kayn', 'kennen', 'khazix', 'kindred', 'kled', 'kogmaw', 'leblanc', 'lee_sin', 'leona', 'lissandra', 'lucian', 'lulu', 'lux', 'malphite', 'malzahar', 'maokai', 'master_yi', 'miss_fortune', 'mordekaiser', 'morgana', 'nami', 'nasus', 'nautilus', 'nidalee', 'nocturne', 'nunu', 'olaf', 'orianna', 'ornn', 'pantheon', 'poppy', 'pyke', 'quinn', 'rakan', 'rammus', 'reksai', 'renekton', 'rengar', 'riven', 'rumble', 'ryze', 'sejuani', 'shaco', 'shen', 'shyvana', 'singed', 'sion', 'sivir', 'skarner', 'sona', 'soraka', 'swain', 'syndra', 'tahm_kench', 'taliyah', 'talon', 'taric', 'teemo', 'thresh', 'tristana', 'trundle', 'tryndamere', 'twisted_fate', 'twitch', 'udyr', 'urgot', 'varus', 'vayne', 'veigar', 'velkoz', 'vi', 'viktor', 'vladimir', 'volibear', 'warwick', 'wukong', 'xayah', 'xerath', 'xin_zhao', 'yasuo', 'yorick', 'zac', 'zed', 'ziggs', 'zilean', 'zoe', 'zyra']

mobafire_names = ['aatrox-114', 'ahri-89', 'akali-50', 'alistar-4', 'amumu-23', 'anivia-25', 'annie-1', 'ashe-13', 
         'aurelion-sol-130', 'azir-121', 'bard-124', 'blitzcrank-34', 'brand-74', 'braum-119', 'caitlyn-67', 
         'camille-134', 'cassiopeia-66', 'chogath-22', 'corki-31', 'darius-98', 'diana-102', 'dr-mundo-26', 
         'draven-99', 'ekko-125', 'elise-106', 'evelynn-19', 'ezreal-47', 'fiddlesticks-38', 'fiora-94', 'fizz-87', 
         'galio-57', 'gangplank-30', 'garen-51', 'gnar-120', 'gragas-45', 'graves-85', 'hecarim-96', 
         'heimerdinger-40', 'illaoi-128', 'irelia-64', 'ivern-133', 'janna-29', 'jarvan-iv-71', 'jax-15', 
         'jayce-100', 'jhin-129', 'jinx-116', 'kaisa-145', 'kalista-122', 'karma-69', 'karthus-21', 
         'kassadin-27', 'katarina-36', 'kayle-2', 'kayn-137', 'kennen-49', 'khazix-105', 'kindred-127', 
         'kled-132', 'kogmaw-54', 'leblanc-63', 'lee-sin-73', 'leona-79', 'lissandra-113', 'lucian-115', 
         'lulu-95', 'lux-62', 'malphite-35', 'malzahar-52', 'maokai-70', 'master-yi-3', 'miss-fortune-59', 
         'mordekaiser-46', 'morgana-16', 'nami-108', 'nasus-37', 'nautilus-93', 'nidalee-42', 'nocturne-72', 
         'nunu-12', 'olaf-53', 'orianna-77', 'ornn-139', 'pantheon-44', 'poppy-43', 'pyke-141', 'quinn-111', 'rakan-136', 
         'rammus-24', 'reksai-123', 'renekton-68', 'rengar-103', 'riven-83', 'rumble-75', 'ryze-5', 'sejuani-91', 
         'shaco-41', 'shen-48', 'shyvana-86', 'singed-18', 'sion-6', 'sivir-7', 'skarner-81', 'sona-60', 'soraka-8', 
         'swain-61', 'syndra-104', 'tahm-kench-126', 'taliyah-131', 'talon-82', 'taric-32', 'teemo-9', 'thresh-110', 
         'tristana-10', 'trundle-65', 'tryndamere-14', 'twisted-fate-28', 'twitch-20', 'udyr-39', 'urgot-58', 
         'varus-97', 'vayne-76', 'veigar-33', 'velkoz-118', 'vi-109', 'viktor-90', 'vladimir-56', 'volibear-88', 
         'warwick-11', 'wukong-80', 'xayah-135', 'xerath-84', 'xin-zhao-55', 'yasuo-117', 'yorick-78', 
         'zac-112', 'zed-107', 'ziggs-92', 'zilean-17', 'zoe-140', 'zyra-101']

abildict = {'aatrox-114':   {'p': 'Deathbringer Stance', 'q': 'The Darkin Blade', 'w': 'Infernal Chains', 
                            'e': 'Umbral Dash', 'r': 'World Ender'}, 
            'ahri-89':      {'p': 'Vastayan Grace', 'q': 'Orb of Deception', 
                            'w': 'Fox-Fire', 'e': 'Charm', 'r': 'Spirit Rush'}, 
            'akali-50':     {'p': 'Twin Disciplines', 'q': 'Mark of the Assassin', 'w': 'Twilight Shroud', 
                            'e': 'Crescent Slash', 'r': 'Shadow Dance'}, 
            'alistar-4':    {'p': 'Triumphant Roar', 'q': 'Pulverize', 'w': 'Headbutt', 
                            'e': 'Trample', 'r': 'Unbreakable Will'}, 
            'amumu-23':     {'p': 'Cursed Touch', 'q': 'Bandage Toss', 'w': 'Despair', 
                            'e': 'Tantrum', 'r': 'Curse of the Sad Mummy'}, 
            'anivia-25':    {'p': 'Rebirth', 'q': 'Flash Frost', 'w': 'Crystallize', 
                            'e': 'Frostbite', 'r': 'Glacial Storm'},            
            'annie-1':      {'p': 'Pyromania', 'q': 'Disintegrate', 'w': 'Incinerate', 
                            'e': 'Molten Shield', 'r': 'Summon: Tibbers'}, 
            'ashe-13':      {'p': 'Frost Shot', 'q': "Ranger's Focus", 'w': 'Volley', 
                            'e': 'Hawkshot', 'r': 'Enchanted Crystal Arrow'}, 
            'aurelion-sol-130': {'p': 'Center of the Universe', 'q': 'Starsurge', 
                            'w': 'Celestial Expansion', 'e': 'Comet of Legend', 'r': 'Voice of Light'}, 
            'azir-121':     {'p': "Shurima's Legacy", 'q': 'Conquering Sands', 
                            'w': 'Arise!', 'e': 'Shifting Sands', 'r': "Emperor's Divide"}, 
            'bard-124':     {'p': "Traveler's Call", 'q': 'Cosmic Binding', 'w': "Caretaker's Shrine", 
                            'e': 'Magical Journey', 'r': 'Tempered Fate'}, 
            'blitzcrank-34': {'p': 'Mana Barrier', 'q': 'Rocket Grab', 'w': 'Overdrive', 
                            'e': 'Power Fist', 'r': 'Static Field'}, 
            'brand-74':     {'p': 'Blaze', 'q': 'Sear', 'w': 'Pillar of Flame', 
                            'e': 'Conflagration', 'r': 'Pyroclasm'},            
            'braum-119':    {'p': 'Concussive Blows', 'q': "Winter's Bite", 'w': 'Stand Behind Me', 
                            'e': 'Unbreakable', 'r': 'Glacial Fissure'}, 
            'caitlyn-67':   {'p': 'Headshot', 'q': 'Piltover Peacemaker', 'w': 'Yordle Snap Trap', 
                            'e': '90 Caliber Net', 'r': 'Ace in the Hole'}, 
            'camille-134':  {'p': 'Adaptive Defenses', 'q': 'Precision Protocol', 'w': 'Tactical Sweep', 
                            'e': 'Hookshot', 'r': 'The Hextech Ultimatum'}, 
            'cassiopeia-66': {'p': 'Serpentine Grace', 'q': 'Noxious Blast', 'w': 'Miasma', 
                            'e': 'Twin Fang', 'r': 'Petrifying Gaze'}, 
            'chogath-22':   {'p': 'Carnivore', 'q': 'Rupture', 'w': 'Feral Scream', 
                            'e': 'Vorpal Spikes', 'r': 'Feast'},             
            'corki-31':     {'p': 'Hextech Munitions', 'q': 'Phosphorus Bomb', 'w': 'Valkyrie', 'alt_w': 'Special Delivery', 
                            'e': 'Gatling Gun', 'r': 'Missile Barrage'}, 
            'darius-98':    {'p': 'Hemorrhage', 'q': 'Decimate', 'w': 'Crippling Strike', 
                            'e': 'Apprehend', 'r': 'Noxian Guillotine'}, 
            'diana-102':    {'p': 'Moonsilver Blade', 'q': 'Crescent Strike', 'w': 'Pale Cascade', 
                            'e': 'Moonfall', 'r': 'Lunar Rush'}, 
            'dr-mundo-26':  {'p': 'Adrenaline Rush', 'q': 'Infected Cleaver', 'w': 'Burning Agony', 
                            'e': 'Masochism', 'r': 'Sadism'}, 
            'draven-99':    {'p': 'League of Draven', 'q': 'Spinning Axe', 'w': 'Blood Rush', 
                            'e': 'Stand Aside', 'r': 'Whirling Death'}, 
            'ekko-125':     {'p': 'Z-Drive Resonance', 'q': 'Timewinder', 'w': 'Parallel Convergence', 
                            'e': 'Phase Dive', 'r': 'Chronobreak'}, 
            'elise-106':    {'p': 'Spider Queen', 'q': 'Neurotoxin', 'alt_q': 'Venomous Bite', 
                            'w': 'Volatile Spiderling', 'alt_w': 'Skittering Frenzy', 'e': 'Cocoon', 'alt_e': 'Rappel', 
                            'r': 'Spider Form / Human Form'}, 
            'evelynn-19':   {'p': 'Demon Shade', 'q': 'Hate Spike', 'w': 'Allure', 
                            'e': 'Whiplash', 'r': 'Last Caress'},             
            'ezreal-47':    {'p': 'Rising Spell Force', 'q': 'Mystic Shot', 'w': 'Essence Flux', 
                            'e': 'Arcane Shift', 'r': 'Trueshot Barrage'}, 
            'fiddlesticks-38': {'p': 'Dread', 'q': 'Terrify', 'w': 'Drain', 
                            'e': 'Dark Wind', 'r': 'Crowstorm'},             
            'fiora-94':     {'p': "Duelist's Dance", 'q': 'Lunge', 'w': 'Riposte', 
                            'e': 'Bladework', 'r': 'Grand Challenge'},             
            'fizz-87':      {'p': 'Nimble Fighter', 'q': 'Urchin Strike', 'w': 'Seastone Trident', 
                            'e': 'Playful / Trickster', 'r': 'Chum the Waters'}, 
            'galio-57':     {'p': 'Colossal Smash', 'q': 'Winds of War', 'w': 'Shield of Durand', 
                            'e': 'Justice Punch', 'r': "Hero's Entrance"}, 
            'gangplank-30': {'p': 'Trial by Fire', 'q': 'Parrrley', 'w': 'Remove Scurvy', 
                            'e': 'Powder Keg', 'r': 'Cannon Barrage'}, 
            'garen-51':     {'p': 'Perseverance', 'q': 'Decisive Strike', 'w': 'Courage', 
                            'e': 'Judgment', 'r': 'Demacian Justice'}, 
            'gnar-120':     {'p': 'Rage Gene', 'q': 'Boomerang Throw', 'alt_q': 'Boulder Toss', 'w': 'Hyper', 'alt_w': 'Wallop', 
                            'e': 'Hop', 'alt_e': 'Crunch', 'r': 'GNAR!'}, 
            'gragas-45':    {'p': 'Happy Hour', 'q': 'Barrel Roll', 'w': 'Drunken Rage', 
                            'e': 'Body Slam', 'r': 'Explosive Cask'}, 
            'graves-85':    {'p': 'New Destiny', 'q': 'End of the Line', 'w': 'Smoke Screen', 
                            'e': 'Quickdraw', 'r': 'Collateral Damage'}, 
            'hecarim-96':   {'p': 'Warpath', 'q': 'Rampage', 'w': 'Spirit of Dread', 
                            'e': 'Devastating Charge', 'r': 'Onslaught of Shadows'}, 
            'heimerdinger-40': {'p': 'Hextech Affinity', 'q': 'H-28G Evolution Turret', 
                            'w': 'Hextech Micro-Rockets', 'e': 'CH-2 Electron Storm Grenade', 'r': 'UPGRADE!!!'}, 
            'illaoi-128':   {'p': 'Prophet of an Elder God', 'q': 'Tentacle Smash', 'w': 'Harsh Lesson', 
                            'e': 'Test of Spirit', 'r': 'Leap of Faith'}, 
            'irelia-64':    {'p': 'Ionian Fervor', 'q': 'Bladesurge', 'w': 'Defiant Dance', 
                            'e': 'Flawless Duet', 'r': "Vanguard's Edge"}, 
            'ivern-133':    {'p': 'Friend of the Forest', 'q': 'Rootcaller', 'w': 'Brushmaker', 
                            'e': 'Triggerseed', 'r': 'Daisy!'}, 
            'janna-29':     {'p': 'Tailwind', 'q': 'Howling Gale', 'w': 'Zephyr', 
                            'e': 'Eye of the Storm', 'r': 'Monsoon'},             
            'jarvan-iv-71': {'p': 'Martial Cadence', 'q': 'Dragon Strike', 'w': 'Golden Aegis', 
                            'e': 'Demacian Standard', 'r': 'Cataclysm'}, 
            'jax-15':       {'p': 'Relentless Assault', 'q': 'Leap Strike', 'w': 'Empower', 
                            'e': 'Counter Strike', 'r': "Grandmaster's Might"}, 
            'jayce-100':    {'p': 'Hextech Capacitor', 'q': 'To the Skies!', 'alt_q': 'Shock Blast', 
                            'w': 'Lightning Field', 'alt_w': 'Hyper Charge', 'e': 'Thundering Blow', 'alt_e': 'Acceleration Gate', 
                            'r': 'Transform Mercury Cannon', 'alt_r': 'Transform Mercury Hammer'},
            'jhin-129':     {'p': 'Whisper', 'q': 'Dancing Grenade', 'w': 'Deadly Flourish', 
                            'e': 'Captive Audience', 'r': 'Curtain Call'}, 
            'jinx-116':     {'p': 'Get Excited!', 'q': 'Switcheroo!', 'w': 'Zap!', 
                            'e': 'Flame Chompers!', 'r': 'Super Mega Death Rocket!'}, 
            'kaisa-145':    {'p': 'Second Skin', 'q': 'Icathian Rain', 'w': 'Void Seeker', 
                            'e': 'Supercharge', 'r': 'Killer Instinct'}, 
            'kalista-122': {'p': 'Martial Poise', 'q': 'Pierce', 'w': 'Sentinel', 
                            'e': 'Rend', 'r': "Fate's Call"},             
            'karma-69':     {'p': 'Gathering Fire', 'q': 'Inner Flame', 'w': 'Focused Resolve', 
                            'e': 'Inspire', 'r': 'Mantra'}, 
            'karthus-21':   {'p': 'Death Defied', 'q': 'Lay Waste', 'w': 'Wall of Pain', 
                            'e': 'Defile', 'r': 'Requiem'},             
            'kassadin-27': {'p': 'Void Stone', 'q': 'Null Sphere', 'w': 'Nether Blade', 
                            'e': 'Force Pulse', 'r': 'Riftwalk'}, 
            'katarina-36': {'p': 'Voracity', 'q': 'Bouncing Blade', 'w': 'Preparation', 
                            'e': 'Shunpo', 'r': 'Death Lotus'}, 
            'kayle-2':      {'p': 'Holy Fervor', 'q': 'Reckoning', 'w': 'Divine Blessing', 
                            'e': 'Righteous Fury', 'r': 'Intervention'}, 
            'kayn-137':     {'p': 'The Darkin Scythe', 'q': 'Reaping Slash', 'w': "Blade's Reach", 
                            'e': 'Shadow Step', 'r': 'Umbral Trespass'}, 
            'kennen-49':    {'p': 'Mark of the Storm', 'q': 'Thundering Shuriken', 'w': 'Electrical Surge', 
                            'e': 'Lightning Rush', 'r': 'Slicing Maelstrom'}, 
            'khazix-105':   {'p': 'Unseen Threat', 'q': 'Taste Their Fear', 'w': 'Void Spike', 
                            'e': 'Leap', 'r': 'Void Assault'}, 
            'kindred-127': {'p': 'Mark of the Kindred', 'q': 'Dance of Arrows', 
                            'w': "Wolf's Frenzy", 'e': 'Mounting Dread', 'r': "Lamb's Respite"}, 
            'kled-132':     {'p': 'Skaarl the Cowardly Lizard', 'q': 'Beartrap on a Rope', 'alt_q': 'Pocket Pistol', 
                            'w': 'Violent Tendencies', 'e': 'Jousting', 'r': 'Chaaaaaaaarge!!!'}, 
            'kogmaw-54':    {'p': 'Icathian Surprise', 'q': 'Caustic Spittle', 'w': 'Bio-Arcane Barrage', 
                            'e': 'Void Ooze', 'r': 'Living Artillery'}, 
            'leblanc-63':   {'p': 'Mirror Image', 'q': 'Sigil of Malice', 'w': 'Distortion', 
                            'e': 'Ethereal Chains', 'r': 'Mimic'}, 
            'lee-sin-73':   {'p': 'Flurry', 'q': 'Sonic Wave', 'alt_q': 'Resonating Strike', 'w': 'Safeguard', 'alt_w': 'Iron Will', 
                            'e': 'Tempest', 'alt_e': 'Cripple', 'r': "Dragon's Rage"}, 
            'leona-79':     {'p': 'Sunlight', 'q': 'Shield of Daybreak', 'w': 'Eclipse', 
                            'e': 'Zenith Blade', 'r': 'Solar Flare'}, 
            'lissandra-113': {'p': 'Iceborn', 'q': 'Ice Shard', 'w': 'Ring of Frost', 
                            'e': 'Glacial Path', 'r': 'Frozen Tomb'}, 
            'lucian-115':   {'p': 'Lightslinger', 'q': 'Piercing Light', 'w': 'Ardent Blaze', 
                            'e': 'Relentless Pursuit', 'r': 'The Culling'}, 
            'lulu-95':      {'p': 'Pix, Faerie Companion', 'q': 'Glitterlance', 'w': 'Whimsy', 
                            'e': 'Help, Pix!', 'r': 'Wild Growth'}, 
            'lux-62':       {'p': 'Illumination', 'q': 'Light Binding', 'w': 'Prismatic Barrier', 
                            'e': 'Lucent Singularity', 'r': 'Final Spark'}, 
            'malphite-35': {'p': 'Granite Shield', 'q': 'Seismic Shard', 'w': 'Brutal Strikes', 
                            'e': 'Ground Slam', 'r': 'Unstoppable Force'}, 
            'malzahar-52': {'p': 'Void Shift', 'q': 'Call of the Void', 'w': 'Void Swarm', 
                            'e': 'Malefic Visions', 'r': 'Nether Grasp'}, 
            'maokai-70':    {'p': 'Sap Magic', 'q': 'Bramble Smash', 'w': 'Twisted Advance', 
                            'e': 'Sapling Toss', 'r': "Nature's Grasp"}, 
            'master-yi-3':  {'p': 'Double Strike', 'q': 'Alpha Strike', 'w': 'Meditate', 
                            'e': 'Wuju Style', 'r': 'Highlander'}, 
            'miss-fortune-59': {'p': 'Love Tap', 'q': 'Double Up', 'w': 'Strut',    
                            'e': 'Make It Rain', 'r': 'Bullet Time'},             
            'mordekaiser-46': {'p': 'Iron Man', 'q': 'Mace of Spades', 'w': 'Harvester of Sorrow', 
                            'e': 'Siphon of Destruction', 'r': 'Children of the Grave'}, 
            'morgana-16':   {'p': 'Soul Siphon', 'q': 'Dark Binding', 'w': 'Tormented Soil', 
                            'e': 'Black Shield', 'r': 'Soul Shackles'}, 
            'nami-108':     {'p': 'Surging Tides', 'q': 'Aqua Prison', 'w': 'Ebb and Flow', 
                            'e': "Tidecaller's Blessing", 'r': 'Tidal Wave'}, 
            'nasus-37':     {'p': 'Soul Eater', 'q': 'Siphoning Strike', 'w': 'Wither', 
                            'e': 'Spirit Fire', 'r': 'Fury of the Sands'}, 
            'nautilus-93':  {'p': 'Staggering Blow', 'q': 'Dredge Line', 'w': "Titan's Wrath", 
                            'e': 'Riptide', 'r': 'Depth Charge'}, 
            'nidalee-42':   {'p': 'Prowl', 'q': 'Javelin Toss', 'alt_q': 'Takedown', 'w': 'Bushwhack', 'alt_w': 'Pounce', 
                            'e': 'Primal Surge', 'alt_e': 'Swipe', 'r': 'Aspect of the Cougar'}, 
            'nocturne-72':  {'p': 'Umbra Blades', 'q': 'Duskbringer', 'w': 'Shroud of Darkness', 
                            'e': 'Unspeakable Horror', 'r': 'Paranoia'}, 
            'nunu-12':      {'p': 'Visionary', 'q': 'Consume', 'w': 'Blood Boil', 
                            'e': 'Ice Blast', 'r': 'Absolute Zero'},             
            'olaf-53':      {'p': 'Berserker Rage', 'q': 'Undertow', 'w': 'Vicious Strikes', 
                            'e': 'Reckless Swing', 'r': 'Ragnarok'}, 
            'orianna-77':   {'p': 'Clockwork Windup', 'q': 'Command: Attack', 'w': 'Command: Dissonance', 
                            'e': 'Command: Protect', 'r': 'Command: Shockwave'}, 
            'ornn-139':     {'p': 'Living Forge', 'q': 'Volcanic Rupture', 'w': 'Bellows Breath', 
                            'e': 'Searing Charge', 'r': 'Call of the Forge God'}, 
            'pantheon-44':  {'p': 'Aegis Protection', 'q': 'Spear Shot', 'w': 'Aegis of Zeonia', 
                            'e': 'Heartseeker Strike', 'r': 'Grand Skyfall'}, 
            'poppy-43':     {'p': 'Iron Ambassador', 'q': 'Hammer Shock', 'w': 'Steadfast Presence', 
                            'e': 'Heroic Charge', 'r': "Keeper's Verdict"}, 
            'pyke-141':     {'p': 'Gift of the Drowned Ones', 'q': 'Bone Skewer', 'w': 'Ghostwater Dive', 
                            'e': 'Phantom Undertow', 'r': "Death from Below"}, 
            'quinn-111':    {'p': 'Harrier', 'q': 'Blinding Assault', 'w': 'Heightened Senses', 
                            'e': 'Vault', 'r': 'Behind Enemy Lines', 'alt_r': 'Skystrike'}, 
            'rakan-136':    {'p': 'Fey Feathers', 'q': 'Gleaming Quill', 'w': 'Grand Entrance', 
                            'e': 'Battle Dance', 'r': 'The Quickness'}, 
            'rammus-24':    {'p': 'Spiked Shell', 'q': 'Powerball', 'w': 'Defensive Ball Curl', 
                            'e': 'Frenzying Taunt', 'r': 'Tremors'}, 
            'reksai-123':   {'p': "Fury of the Xer'Sai", 'q': "Queen's Wrath", 'alt_q': "Prey Seeker", 'w': 'Burrow', 'alt_w': 'Unburrow', 
                            'e': 'Furious Bite', 'alt_e': 'Tunnel', 'r': 'Void Rush'}, 
            'renekton-68':  {'p': 'Reign of Anger', 'q': 'Cull the Meek', 'w': 'Ruthless Predator', 
                            'e': 'Slice and Dice', 'r': 'Dominus'}, 
            'rengar-103':   {'p': 'Unseen Predator', 'q': 'Savagery', 'w': 'Battle Roar', 
                            'e': 'Bola Strike', 'r': 'Thrill of the Hunt'}, 
            'riven-83':     {'p': 'Runic Blade', 'q': 'Broken Wings', 'w': 'Ki Burst', 
                            'e': 'Valor', 'r': 'Blade of the Exile', 'alt_r': 'Wind Slash'}, 
            'rumble-75':    {'p': 'Junkyard Titan', 'q': 'Flamespitter', 'w': 'Scrap Shield', 
                            'e': 'Electro Harpoon', 'r': 'The Equalizer'}, 
            'ryze-5':       {'p': 'Arcane Mastery', 'q': 'Overload', 'w': 'Rune Prison', 
                            'e': 'Spell Flux', 'r': 'Realm Warp'},             
            'sejuani-91':   {'p': 'Fury of the North', 'q': 'Arctic Assault', 'w': "Winter's Wrath", 
                            'e': 'Permafrost', 'r': 'Glacial Prison'}, 
            'shaco-41':     {'p': 'Backstab', 'q': 'Deceive', 'w': 'Jack in the Box', 
                            'e': 'Two-Shiv Poison', 'r': 'Hallucinate'}, 
            'shen-48':      {'p': 'Ki Barrier', 'q': 'Twilight Assault', 'w': "Spirit's Refuge", 
                            'e': 'Shadow Dash', 'r': 'Stand United'}, 
            'shyvana-86':   {'p': 'Fury of the Dragonborn', 'q': 'Twin Bite', 'w': 'Burnout', 
                            'e': 'Flame Breath', 'r': "Dragon's Descent"}, 
            'singed-18':    {'p': 'Noxious Slipstream', 'q': 'Poison Trail', 'w': 'Mega Adhesive', 
                            'e': 'Fling', 'r': 'Insanity Potion'}, 
            'sion-6':       {'p': 'Glory in Death', 'alt_p': 'Death Surge', 'q': 'Decimating Smash', 'w': 'Soul Furnace', 
                            'e': 'Roar of the Slayer', 'r': 'Unstoppable Onslaught'}, 
            'sivir-7':      {'p': 'Fleet of Foot', 'q': 'Boomerang Blade', 'w': 'Ricochet', 
                            'e': 'Spell Shield', 'r': 'On the Hunt'}, 
            'skarner-81':   {'p': 'Crystal Spires', 'q': 'Crystal Slash', 'w': 'Crystalline Exoskeleton', 
                            'e': 'Fracture', 'r': 'Impale'}, 
            'sona-60':      {'p': 'Power Chord', 'q': 'Hymn of Valor', 'w': 'Aria of Perseverance', 
                            'e': 'Song of Celerity', 'r': 'Crescendo'}, 
            'soraka-8':     {'p': 'Salvation', 'q': 'Starcall', 'w': 'Astral Infusion', 
                            'e': 'Equinox', 'r': 'Wish'},             
            'swain-61':     {'p': 'Ravenous Flock', 'q': "Death's Hand", 'w': 'Vision of Empire', 
                            'e': 'Nevermove', 'r': 'Demonic Ascension', 'alt_r': 'Demonflare'}, 
            'syndra-104':   {'p': 'Transcendent', 'q': 'Dark Sphere', 'w': 'Force of Will', 
                            'e': 'Scatter the Weak', 'r': 'Unleashed Power'}, 
            'tahm-kench-126': {'p': 'An Acquired Taste', 'q': 'Tongue Lash', 'w': 'Devour', 'alt_w': 'Regurgitate', 
                            'e': 'Thick Skin', 'r': 'Abyssal Voyage'}, 
            'taliyah-131':  {'p': 'Rock Surfing', 'q': 'Threaded Volley', 'w': 'Seismic Shove', 
                            'e': 'Unraveled Earth', 'r': "Weaver's Wall"}, 
            'talon-82':     {'p': "Blade's End", 'q': 'Noxian Diplomacy', 'w': 'Rake', 
                            'e': "Assassin's Path", 'r': 'Shadow Assault'}, 
            'taric-32':     {'p': 'Bravado', 'q': "Starlight's Touch", 'w': 'Bastion', 
                            'e': 'Dazzle', 'r': 'Cosmic Radiance'},             
            'teemo-9':      {'p': 'Guerrilla Warfare', 'q': 'Blinding Dart', 'w': 'Move Quick', 
                            'e': 'Toxic Shot', 'r': 'Noxious Trap'}, 
            'thresh-110':   {'p': 'Damnation', 'q': 'Death Sentence', 'w': 'Dark Passage', 
                            'e': 'Flay', 'r': 'The Box'},             
            'tristana-10':  {'p': 'Draw a Bead', 'q': 'Rapid Fire', 'w': 'Rocket Jump', 
                            'e': 'Explosive Charge', 'r': 'Buster Shot'}, 
            'trundle-65':   {'p': "King's Tribute", 'q': 'Chomp', 'w': 'Frozen Domain', 
                            'e': 'Pillar of Ice', 'r': 'Subjugate'}, 
            'tryndamere-14': {'p': 'Battle Fury', 'q': 'Bloodlust', 'w': 'Mocking Shout', 
                            'e': 'Spinning Slash', 'r': 'Undying Rage'}, 
            'twisted-fate-28': {'p': 'Loaded Dice', 'q': 'Wild Cards', 'w': 'Pick a Card', 
                            'e': 'Stacked Deck', 'r': 'Destiny'}, 
            'twitch-20':    {'p': 'Deadly Venom', 'q': 'Ambush', 'w': 'Venom Cask', 
                            'e': 'Contaminate', 'r': 'Spray and Pray'}, 
            'udyr-39':      {'p': "Monkey's Agility", 'q': 'Tiger Stance', 'w': 'Turtle Stance', 
                            'e': 'Bear Stance', 'r': 'Phoenix Stance'}, 
            'urgot-58':     {'p': 'Echoing Flames', 'q': 'Corrosive Charge', 'w': 'Purge', 
                            'e': 'Disdain', 'r': 'Fear Beyond Death'}, 
            'varus-97':     {'p': 'Living Vengeance', 'q': 'Piercing Arrow', 'w': 'Blighted Quiver', 
                            'e': 'Hail of Arrows', 'r': 'Chain of Corruption'}, 
            'vayne-76':     {'p': 'Night Hunter', 'q': 'Tumble', 'w': 'Silver Bolts', 
                            'e': 'Condemn', 'r': 'Final Hour'},          
            'veigar-33':    {'p': 'Phenomenal Evil Power', 'q': 'Baleful Strike', 'w': 'Dark Matter', 
                            'e': 'Event Horizon', 'r': 'Primordial Burst'}, 
            'velkoz-118':   {'p': 'Organic Deconstruction', 'q': 'Plasma Fission', 'w': 'Void Rift', 
                            'e': 'Tectonic Disruption', 'r': 'Life Form Disintegration Ray'}, 
            'vi-109':       {'p': 'Blast Shield', 'q': 'Vault Breaker', 'w': 'Denting Blows', 
                            'e': 'Excessive Force', 'r': 'Assault and Battery'}, 
            'viktor-90':    {'p': 'Glorious Evolution', 'q': 'Siphon Power', 'w': 'Gravity Field', 
                            'e': 'Death Ray', 'r': 'Chaos Storm'}, 
            'vladimir-56':  {'p': 'Crimson Pact', 'q': 'Transfusion', 'w': 'Sanguine Pool', 
                            'e': 'Tides of Blood', 'r': 'Hemoplague'}, 
            'volibear-88':  {'p': 'Chosen of the Storm', 'q': 'Rolling Thunder', 'w': 'Frenzy', 
                            'e': 'Majestic Roar', 'r': 'Thunder Claws'}, 
            'warwick-11':   {'p': 'Eternal Hunger', 'q': 'Jaws of the Beast', 'w': 'Blood Hunt', 
                            'e': 'Primal Howl', 'r': 'Infinite Duress'}, 
            'wukong-80':    {'p': 'Stone Skin', 'q': 'Crushing Blow', 'w': 'Decoy', 
                            'e': 'Nimbus Strike', 'r': 'Cyclone'},             
            'xayah-135':    {'p': 'Clean Cuts', 'q': 'Double Daggers', 'w': 'Deadly Plumage', 
                            'e': 'Bladecaller', 'r': 'Featherstorm'}, 
            'xerath-84':    {'p': 'Mana Surge', 'q': 'Arcanopulse', 'w': 'Eye of Destruction', 
                            'e': 'Shocking Orb', 'r': 'Rite of the Arcane'}, 
            'xin-zhao-55':  {'p': 'Determination', 'q': 'Three Talon Strike', 'w': 'Wind Becomes Lightning', 
                            'e': 'Audacious Charge', 'r': 'Crescent Guard'}, 
            'yasuo-117':    {'p': 'Way of the Wanderer', 'q': 'Steel Tempest', 'w': 'Wind Wall', 
                            'e': 'Sweeping Blade', 'r': 'Last Breath'}, 
            'yorick-78':    {'p': 'Shepherd of Souls', 'q': 'Last Rites', 'alt_q': 'Awakening', 'w': 'Dark Procession', 
                            'e': 'Mourning Mist', 'r': 'Eulogy of the Isles'}, 
            'zac-112':      {'p': 'Cell Division', 'q': 'Stretching Strike', 'w': 'Unstable Matter', 
                            'e': 'Elastic Slingshot', 'r': "Let's Bounce!"}, 
            'zed-107':      {'p': 'Contempt for the Weak', 'q': 'Razor Shuriken', 'w': 'Living Shadow', 
                            'e': 'Shadow Slash', 'r': 'Death Mark'}, 
            'ziggs-92':     {'p': 'Short Fuse', 'q': 'Bouncing Bomb', 'w': 'Satchel Charge', 
                            'e': 'Hexplosive Minefield', 'r': 'Mega Inferno Bomb'}, 
            'zilean-17':    {'p': 'Time in a Bottle', 'q': 'Time Bomb', 'w': 'Rewind', 
                            'e': 'Time Warp', 'r': 'Chronoshift'}, 
            'zoe-140':      {'p': 'More Sparkles!', 'q': 'Paddle Star', 'w': 'Spell Thief', 
                            'e': 'Sleepy Trouble Bubble', 'r': 'Portal Jump'}, 
            'zyra-101':     {'p': 'Garden of Thorns', 'q': 'Deadly Spines', 'w': 'Rampant Growth', 
                            'e': 'Grasping Roots', 'r': 'Stranglethorns'}}

abildict2 = {'Aatrox':   {'p': 'Deathbringer Stance', 'q': 'The Darkin Blade', 'w': 'Infernal Chains', 
                            'e': 'Umbral Dash', 'r': 'World Ender'}, 
            'Ahri':      {'p': 'Vastayan Grace', 'q': 'Orb of Deception', 
                            'w': 'Fox-Fire', 'e': 'Charm', 'r': 'Spirit Rush'}, 
            'Akali':     {'p': 'Twin Disciplines', 'q': 'Mark of the Assassin', 'w': 'Twilight Shroud', 
                            'e': 'Crescent Slash', 'r': 'Shadow Dance'}, 
            'Alistar':    {'p': 'Triumphant Roar', 'q': 'Pulverize', 'w': 'Headbutt', 
                            'e': 'Trample', 'r': 'Unbreakable Will'}, 
            'Amumu':     {'p': 'Cursed Touch', 'q': 'Bandage Toss', 'w': 'Despair', 
                            'e': 'Tantrum', 'r': 'Curse of the Sad Mummy'}, 
            'Anivia':    {'p': 'Rebirth', 'q': 'Flash Frost', 'w': 'Crystallize', 
                            'e': 'Frostbite', 'r': 'Glacial Storm'},            
            'Annie':      {'p': 'Pyromania', 'q': 'Disintegrate', 'w': 'Incinerate', 
                            'e': 'Molten Shield', 'r': 'Summon: Tibbers'}, 
            'Ashe':      {'p': 'Frost Shot', 'q': "Ranger's Focus", 'w': 'Volley', 
                            'e': 'Hawkshot', 'r': 'Enchanted Crystal Arrow'}, 
            'Aurelion_Sol': {'p': 'Center of the Universe', 'q': 'Starsurge', 
                            'w': 'Celestial Expansion', 'e': 'Comet of Legend', 'r': 'Voice of Light'}, 
            'Azir':     {'p': "Shurima's Legacy", 'q': 'Conquering Sands', 
                            'w': 'Arise!', 'e': 'Shifting Sands', 'r': "Emperor's Divide"}, 
            'Bard':     {'p': "Traveler's Call", 'q': 'Cosmic Binding', 'w': "Caretaker's Shrine", 
                            'e': 'Magical Journey', 'r': 'Tempered Fate'}, 
            'Blitzcrank': {'p': 'Mana Barrier', 'q': 'Rocket Grab', 'w': 'Overdrive', 
                            'e': 'Power Fist', 'r': 'Static Field'}, 
            'Brand':     {'p': 'Blaze', 'q': 'Sear', 'w': 'Pillar of Flame', 
                            'e': 'Conflagration', 'r': 'Pyroclasm'},            
            'Braum':    {'p': 'Concussive Blows', 'q': "Winter's Bite", 'w': 'Stand Behind Me', 
                            'e': 'Unbreakable', 'r': 'Glacial Fissure'}, 
            'Caitlyn':   {'p': 'Headshot', 'q': 'Piltover Peacemaker', 'w': 'Yordle Snap Trap', 
                            'e': '90 Caliber Net', 'r': 'Ace in the Hole'}, 
            'Camille':  {'p': 'Adaptive Defenses', 'q': 'Precision Protocol', 'w': 'Tactical Sweep', 
                            'e': 'Hookshot', 'r': 'The Hextech Ultimatum'}, 
            'Cassiopeia': {'p': 'Serpentine Grace', 'q': 'Noxious Blast', 'w': 'Miasma', 
                            'e': 'Twin Fang', 'r': 'Petrifying Gaze'}, 
            "Cho'Gath":   {'p': 'Carnivore', 'q': 'Rupture', 'w': 'Feral Scream', 
                            'e': 'Vorpal Spikes', 'r': 'Feast'},             
            'Corki':     {'p': 'Hextech Munitions', 'q': 'Phosphorus Bomb', 'w': 'Valkyrie', 'alt_w': 'Special Delivery', 
                            'e': 'Gatling Gun', 'r': 'Missile Barrage'}, 
            'Darius':    {'p': 'Hemorrhage', 'q': 'Decimate', 'w': 'Crippling Strike', 
                            'e': 'Apprehend', 'r': 'Noxian Guillotine'}, 
            'Diana':    {'p': 'Moonsilver Blade', 'q': 'Crescent Strike', 'w': 'Pale Cascade', 
                            'e': 'Moonfall', 'r': 'Lunar Rush'}, 
            'Dr._Mundo':  {'p': 'Adrenaline Rush', 'q': 'Infected Cleaver', 'w': 'Burning Agony', 
                            'e': 'Masochism', 'r': 'Sadism'}, 
            'Draven':    {'p': 'League of Draven', 'q': 'Spinning Axe', 'w': 'Blood Rush', 
                            'e': 'Stand Aside', 'r': 'Whirling Death'}, 
            'Ekko':     {'p': 'Z-Drive Resonance', 'q': 'Timewinder', 'w': 'Parallel Convergence', 
                            'e': 'Phase Dive', 'r': 'Chronobreak'}, 
            'Elise':    {'p': 'Spider Queen', 'q': 'Neurotoxin', 'alt_q': 'Venomous Bite', 
                            'w': 'Volatile Spiderling', 'alt_w': 'Skittering Frenzy', 'e': 'Cocoon', 'alt_e': 'Rappel', 
                            'r': 'Spider Form / Human Form'}, 
            'Evelynn':   {'p': 'Demon Shade', 'q': 'Hate Spike', 'w': 'Allure', 
                            'e': 'Whiplash', 'r': 'Last Caress'},             
            'Ezreal':    {'p': 'Rising Spell Force', 'q': 'Mystic Shot', 'w': 'Essence Flux', 
                            'e': 'Arcane Shift', 'r': 'Trueshot Barrage'}, 
            'Fiddlesticks': {'p': 'Dread', 'q': 'Terrify', 'w': 'Drain', 
                            'e': 'Dark Wind', 'r': 'Crowstorm'},             
            'Fiora':     {'p': "Duelist's Dance", 'q': 'Lunge', 'w': 'Riposte', 
                            'e': 'Bladework', 'r': 'Grand Challenge'},             
            'Fizz':      {'p': 'Nimble Fighter', 'q': 'Urchin Strike', 'w': 'Seastone Trident', 
                            'e': 'Playful / Trickster', 'r': 'Chum the Waters'}, 
            'Galio':     {'p': 'Colossal Smash', 'q': 'Winds of War', 'w': 'Shield of Durand', 
                            'e': 'Justice Punch', 'r': "Hero's Entrance"}, 
            'Gangplank': {'p': 'Trial by Fire', 'q': 'Parrrley', 'w': 'Remove Scurvy', 
                            'e': 'Powder Keg', 'r': 'Cannon Barrage'}, 
            'Garen':     {'p': 'Perseverance', 'q': 'Decisive Strike', 'w': 'Courage', 
                            'e': 'Judgment', 'r': 'Demacian Justice'}, 
            'Gnar':     {'p': 'Rage Gene', 'q': 'Boomerang Throw', 'alt_q': 'Boulder Toss', 'w': 'Hyper', 'alt_w': 'Wallop', 
                            'e': 'Hop', 'alt_e': 'Crunch', 'r': 'GNAR!'}, 
            'Gragas':    {'p': 'Happy Hour', 'q': 'Barrel Roll', 'w': 'Drunken Rage', 
                            'e': 'Body Slam', 'r': 'Explosive Cask'}, 
            'Graves':    {'p': 'New Destiny', 'q': 'End of the Line', 'w': 'Smoke Screen', 
                            'e': 'Quickdraw', 'r': 'Collateral Damage'}, 
            'Hecarim':   {'p': 'Warpath', 'q': 'Rampage', 'w': 'Spirit of Dread', 
                            'e': 'Devastating Charge', 'r': 'Onslaught of Shadows'}, 
            'Heimerdinger': {'p': 'Hextech Affinity', 'q': 'H-28G Evolution Turret', 
                            'w': 'Hextech Micro-Rockets', 'e': 'CH-2 Electron Storm Grenade', 'r': 'UPGRADE!!!'}, 
            'Illaoi':   {'p': 'Prophet of an Elder God', 'q': 'Tentacle Smash', 'w': 'Harsh Lesson', 
                            'e': 'Test of Spirit', 'r': 'Leap of Faith'}, 
            'Irelia':    {'p': 'Ionian Fervor', 'q': 'Bladesurge', 'w': 'Defiant Dance', 
                            'e': 'Flawless Duet', 'r': "Vanguard's Edge"}, 
            'Ivern':    {'p': 'Friend of the Forest', 'q': 'Rootcaller', 'w': 'Brushmaker', 
                            'e': 'Triggerseed', 'r': 'Daisy!'}, 
            'Janna':     {'p': 'Tailwind', 'q': 'Howling Gale', 'w': 'Zephyr', 
                            'e': 'Eye of the Storm', 'r': 'Monsoon'},             
            'Jarvan_IV': {'p': 'Martial Cadence', 'q': 'Dragon Strike', 'w': 'Golden Aegis', 
                            'e': 'Demacian Standard', 'r': 'Cataclysm'}, 
            'Jax':       {'p': 'Relentless Assault', 'q': 'Leap Strike', 'w': 'Empower', 
                            'e': 'Counter Strike', 'r': "Grandmaster's Might"}, 
            'Jayce':    {'p': 'Hextech Capacitor', 'q': 'To the Skies!', 'alt_q': 'Shock Blast', 
                            'w': 'Lightning Field', 'alt_w': 'Hyper Charge', 'e': 'Thundering Blow', 'alt_e': 'Acceleration Gate', 
                            'r': 'Transform Mercury Cannon', 'alt_r': 'Transform Mercury Hammer'},
            'Jhin':     {'p': 'Whisper', 'q': 'Dancing Grenade', 'w': 'Deadly Flourish', 
                            'e': 'Captive Audience', 'r': 'Curtain Call'}, 
            'Jinx':     {'p': 'Get Excited!', 'q': 'Switcheroo!', 'w': 'Zap!', 
                            'e': 'Flame Chompers!', 'r': 'Super Mega Death Rocket!'}, 
            "Kai'Sa":    {'p': 'Second Skin', 'q': 'Icathian Rain', 'w': 'Void Seeker', 
                            'e': 'Supercharge', 'r': 'Killer Instinct'}, 
            'Kalista': {'p': 'Martial Poise', 'q': 'Pierce', 'w': 'Sentinel', 
                            'e': 'Rend', 'r': "Fate's Call"},             
            'Karma':     {'p': 'Gathering Fire', 'q': 'Inner Flame', 'w': 'Focused Resolve', 
                            'e': 'Inspire', 'r': 'Mantra'}, 
            'Karthus':   {'p': 'Death Defied', 'q': 'Lay Waste', 'w': 'Wall of Pain', 
                            'e': 'Defile', 'r': 'Requiem'},             
            'Kassadin': {'p': 'Void Stone', 'q': 'Null Sphere', 'w': 'Nether Blade', 
                            'e': 'Force Pulse', 'r': 'Riftwalk'}, 
            'Katarina': {'p': 'Voracity', 'q': 'Bouncing Blade', 'w': 'Preparation', 
                            'e': 'Shunpo', 'r': 'Death Lotus'}, 
            'Kayle':      {'p': 'Holy Fervor', 'q': 'Reckoning', 'w': 'Divine Blessing', 
                            'e': 'Righteous Fury', 'r': 'Intervention'}, 
            'Kayn':     {'p': 'The Darkin Scythe', 'q': 'Reaping Slash', 'w': "Blade's Reach", 
                            'e': 'Shadow Step', 'r': 'Umbral Trespass'}, 
            'Kennen':    {'p': 'Mark of the Storm', 'q': 'Thundering Shuriken', 'w': 'Electrical Surge', 
                            'e': 'Lightning Rush', 'r': 'Slicing Maelstrom'}, 
            "Kha'Zix":   {'p': 'Unseen Threat', 'q': 'Taste Their Fear', 'w': 'Void Spike', 
                            'e': 'Leap', 'r': 'Void Assault'}, 
            'Kindred': {'p': 'Mark of the Kindred', 'q': 'Dance of Arrows', 
                            'w': "Wolf's Frenzy", 'e': 'Mounting Dread', 'r': "Lamb's Respite"}, 
            'Kled':     {'p': 'Skaarl the Cowardly Lizard', 'q': 'Beartrap on a Rope', 'alt_q': 'Pocket Pistol', 
                            'w': 'Violent Tendencies', 'e': 'Jousting', 'r': 'Chaaaaaaaarge!!!'}, 
            "Kog'Maw":    {'p': 'Icathian Surprise', 'q': 'Caustic Spittle', 'w': 'Bio-Arcane Barrage', 
                            'e': 'Void Ooze', 'r': 'Living Artillery'}, 
            'LeBlanc':   {'p': 'Mirror Image', 'q': 'Sigil of Malice', 'w': 'Distortion', 
                            'e': 'Ethereal Chains', 'r': 'Mimic'}, 
            'Lee_Sin':   {'p': 'Flurry', 'q': 'Sonic Wave', 'alt_q': 'Resonating Strike', 'w': 'Safeguard', 'alt_w': 'Iron Will', 
                            'e': 'Tempest', 'alt_e': 'Cripple', 'r': "Dragon's Rage"}, 
            'Leona':     {'p': 'Sunlight', 'q': 'Shield of Daybreak', 'w': 'Eclipse', 
                            'e': 'Zenith Blade', 'r': 'Solar Flare'}, 
            'Lissandra': {'p': 'Iceborn', 'q': 'Ice Shard', 'w': 'Ring of Frost', 
                            'e': 'Glacial Path', 'r': 'Frozen Tomb'}, 
            'Lucian':   {'p': 'Lightslinger', 'q': 'Piercing Light', 'w': 'Ardent Blaze', 
                            'e': 'Relentless Pursuit', 'r': 'The Culling'}, 
            'Lulu':      {'p': 'Pix, Faerie Companion', 'q': 'Glitterlance', 'w': 'Whimsy', 
                            'e': 'Help, Pix!', 'r': 'Wild Growth'}, 
            'Lux':       {'p': 'Illumination', 'q': 'Light Binding', 'w': 'Prismatic Barrier', 
                            'e': 'Lucent Singularity', 'r': 'Final Spark'}, 
            'Malphite': {'p': 'Granite Shield', 'q': 'Seismic Shard', 'w': 'Brutal Strikes', 
                            'e': 'Ground Slam', 'r': 'Unstoppable Force'}, 
            'Malzahar': {'p': 'Void Shift', 'q': 'Call of the Void', 'w': 'Void Swarm', 
                            'e': 'Malefic Visions', 'r': 'Nether Grasp'}, 
            'Maokai':    {'p': 'Sap Magic', 'q': 'Bramble Smash', 'w': 'Twisted Advance', 
                            'e': 'Sapling Toss', 'r': "Nature's Grasp"}, 
            'Master_Yi':  {'p': 'Double Strike', 'q': 'Alpha Strike', 'w': 'Meditate', 
                            'e': 'Wuju Style', 'r': 'Highlander'}, 
            'Miss_Fortune': {'p': 'Love Tap', 'q': 'Double Up', 'w': 'Strut',    
                            'e': 'Make It Rain', 'r': 'Bullet Time'},             
            'Mordekaiser': {'p': 'Iron Man', 'q': 'Mace of Spades', 'w': 'Harvester of Sorrow', 
                            'e': 'Siphon of Destruction', 'r': 'Children of the Grave'}, 
            'Morgana':   {'p': 'Soul Siphon', 'q': 'Dark Binding', 'w': 'Tormented Soil', 
                            'e': 'Black Shield', 'r': 'Soul Shackles'}, 
            'Nami':     {'p': 'Surging Tides', 'q': 'Aqua Prison', 'w': 'Ebb and Flow', 
                            'e': "Tidecaller's Blessing", 'r': 'Tidal Wave'}, 
            'Nasus':     {'p': 'Soul Eater', 'q': 'Siphoning Strike', 'w': 'Wither', 
                            'e': 'Spirit Fire', 'r': 'Fury of the Sands'}, 
            'Nautilus':  {'p': 'Staggering Blow', 'q': 'Dredge Line', 'w': "Titan's Wrath", 
                            'e': 'Riptide', 'r': 'Depth Charge'}, 
            'Nidalee':   {'p': 'Prowl', 'q': 'Javelin Toss', 'alt_q': 'Takedown', 'w': 'Bushwhack', 'alt_w': 'Pounce', 
                            'e': 'Primal Surge', 'alt_e': 'Swipe', 'r': 'Aspect of the Cougar'}, 
            'Nocturne':  {'p': 'Umbra Blades', 'q': 'Duskbringer', 'w': 'Shroud of Darkness', 
                            'e': 'Unspeakable Horror', 'r': 'Paranoia'}, 
            'Nunu':      {'p': 'Visionary', 'q': 'Consume', 'w': 'Blood Boil', 
                            'e': 'Ice Blast', 'r': 'Absolute Zero'},             
            'Olaf':      {'p': 'Berserker Rage', 'q': 'Undertow', 'w': 'Vicious Strikes', 
                            'e': 'Reckless Swing', 'r': 'Ragnarok'}, 
            'Orianna':   {'p': 'Clockwork Windup', 'q': 'Command: Attack', 'w': 'Command: Dissonance', 
                            'e': 'Command: Protect', 'r': 'Command: Shockwave'}, 
            'Ornn':     {'p': 'Living Forge', 'q': 'Volcanic Rupture', 'w': 'Bellows Breath', 
                            'e': 'Searing Charge', 'r': 'Call of the Forge God'}, 
            'Pantheon': {'p': 'Aegis Protection', 'q': 'Spear Shot', 'w': 'Aegis of Zeonia', 
                            'e': 'Heartseeker Strike', 'r': 'Grand Skyfall'}, 
            'Poppy':     {'p': 'Iron Ambassador', 'q': 'Hammer Shock', 'w': 'Steadfast Presence', 
                            'e': 'Heroic Charge', 'r': "Keeper's Verdict"}, 
            'Pyke':     {'p': 'Gift of the Drowned Ones', 'q': 'Bone Skewer', 'w': 'Ghostwater Dive', 
                            'e': 'Phantom Undertow', 'r': "Death from Below"},
            'Quinn':    {'p': 'Harrier', 'q': 'Blinding Assault', 'w': 'Heightened Senses', 
                            'e': 'Vault', 'r': 'Behind Enemy Lines', 'alt_r': 'Skystrike'}, 
            'Rakan':    {'p': 'Fey Feathers', 'q': 'Gleaming Quill', 'w': 'Grand Entrance', 
                            'e': 'Battle Dance', 'r': 'The Quickness'}, 
            'Rammus':    {'p': 'Spiked Shell', 'q': 'Powerball', 'w': 'Defensive Ball Curl', 
                            'e': 'Frenzying Taunt', 'r': 'Tremors'}, 
            "Rek'Sai":   {'p': "Fury of the Xer'Sai", 'q': "Queen's Wrath", 'alt_q': "Prey Seeker", 'w': 'Burrow', 'alt_w': 'Unburrow', 
                            'e': 'Furious Bite', 'alt_e': 'Tunnel', 'r': 'Void Rush'}, 
            'Renekton':  {'p': 'Reign of Anger', 'q': 'Cull the Meek', 'w': 'Ruthless Predator', 
                            'e': 'Slice and Dice', 'r': 'Dominus'}, 
            'Rengar':   {'p': 'Unseen Predator', 'q': 'Savagery', 'w': 'Battle Roar', 
                            'e': 'Bola Strike', 'r': 'Thrill of the Hunt'}, 
            'Riven':     {'p': 'Runic Blade', 'q': 'Broken Wings', 'w': 'Ki Burst', 
                            'e': 'Valor', 'r': 'Blade of the Exile', 'alt_r': 'Wind Slash'}, 
            'Rumble':    {'p': 'Junkyard Titan', 'q': 'Flamespitter', 'w': 'Scrap Shield', 
                            'e': 'Electro Harpoon', 'r': 'The Equalizer'}, 
            'Ryze':       {'p': 'Arcane Mastery', 'q': 'Overload', 'w': 'Rune Prison', 
                            'e': 'Spell Flux', 'r': 'Realm Warp'},             
            'Sejuani':   {'p': 'Fury of the North', 'q': 'Arctic Assault', 'w': "Winter's Wrath", 
                            'e': 'Permafrost', 'r': 'Glacial Prison'}, 
            'Shaco':     {'p': 'Backstab', 'q': 'Deceive', 'w': 'Jack in the Box', 
                            'e': 'Two-Shiv Poison', 'r': 'Hallucinate'}, 
            'Shen':      {'p': 'Ki Barrier', 'q': 'Twilight Assault', 'w': "Spirit's Refuge", 
                            'e': 'Shadow Dash', 'r': 'Stand United'}, 
            'Shyvana':   {'p': 'Fury of the Dragonborn', 'q': 'Twin Bite', 'w': 'Burnout', 
                            'e': 'Flame Breath', 'r': "Dragon's Descent"}, 
            'Singed':    {'p': 'Noxious Slipstream', 'q': 'Poison Trail', 'w': 'Mega Adhesive', 
                            'e': 'Fling', 'r': 'Insanity Potion'}, 
            'Sion':       {'p': 'Glory in Death', 'alt_p': 'Death Surge', 'q': 'Decimating Smash', 'w': 'Soul Furnace', 
                            'e': 'Roar of the Slayer', 'r': 'Unstoppable Onslaught'}, 
            'Sivir':      {'p': 'Fleet of Foot', 'q': 'Boomerang Blade', 'w': 'Ricochet', 
                            'e': 'Spell Shield', 'r': 'On the Hunt'}, 
            'Skarner':   {'p': 'Crystal Spires', 'q': 'Crystal Slash', 'w': 'Crystalline Exoskeleton', 
                            'e': 'Fracture', 'r': 'Impale'}, 
            'Sona':      {'p': 'Power Chord', 'q': 'Hymn of Valor', 'w': 'Aria of Perseverance', 
                            'e': 'Song of Celerity', 'r': 'Crescendo'}, 
            'Soraka':     {'p': 'Salvation', 'q': 'Starcall', 'w': 'Astral Infusion', 
                            'e': 'Equinox', 'r': 'Wish'},             
            'Swain':     {'p': 'Ravenous Flock', 'q': "Death's Hand", 'w': 'Vision of Empire', 
                            'e': 'Nevermove', 'r': 'Demonic Ascension', 'alt_r': 'Demonflare'}, 
            'Syndra':   {'p': 'Transcendent', 'q': 'Dark Sphere', 'w': 'Force of Will', 
                            'e': 'Scatter the Weak', 'r': 'Unleashed Power'}, 
            'Tahm_Kench': {'p': 'An Acquired Taste', 'q': 'Tongue Lash', 'w': 'Devour', 'alt_w': 'Regurgitate', 
                            'e': 'Thick Skin', 'r': 'Abyssal Voyage'}, 
            'Taliyah':  {'p': 'Rock Surfing', 'q': 'Threaded Volley', 'w': 'Seismic Shove', 
                            'e': 'Unraveled Earth', 'r': "Weaver's Wall"}, 
            'Talon':     {'p': "Blade's End", 'q': 'Noxian Diplomacy', 'w': 'Rake', 
                            'e': "Assassin's Path", 'r': 'Shadow Assault'}, 
            'Taric':     {'p': 'Bravado', 'q': "Starlight's Touch", 'w': 'Bastion', 
                            'e': 'Dazzle', 'r': 'Cosmic Radiance'},             
            'Teemo':      {'p': 'Guerrilla Warfare', 'q': 'Blinding Dart', 'w': 'Move Quick', 
                            'e': 'Toxic Shot', 'r': 'Noxious Trap'}, 
            'Thresh':   {'p': 'Damnation', 'q': 'Death Sentence', 'w': 'Dark Passage', 
                            'e': 'Flay', 'r': 'The Box'},             
            'Tristana':  {'p': 'Draw a Bead', 'q': 'Rapid Fire', 'w': 'Rocket Jump', 
                            'e': 'Explosive Charge', 'r': 'Buster Shot'}, 
            'Trundle':   {'p': "King's Tribute", 'q': 'Chomp', 'w': 'Frozen Domain', 
                            'e': 'Pillar of Ice', 'r': 'Subjugate'}, 
            'Tryndamere': {'p': 'Battle Fury', 'q': 'Bloodlust', 'w': 'Mocking Shout', 
                            'e': 'Spinning Slash', 'r': 'Undying Rage'}, 
            'Twisted_Fate': {'p': 'Loaded Dice', 'q': 'Wild Cards', 'w': 'Pick a Card', 
                            'e': 'Stacked Deck', 'r': 'Destiny'}, 
            'Twitch':    {'p': 'Deadly Venom', 'q': 'Ambush', 'w': 'Venom Cask', 
                            'e': 'Contaminate', 'r': 'Spray and Pray'}, 
            'Udyr':      {'p': "Monkey's Agility", 'q': 'Tiger Stance', 'w': 'Turtle Stance', 
                            'e': 'Bear Stance', 'r': 'Phoenix Stance'}, 
            'Urgot':     {'p': 'Echoing Flames', 'q': 'Corrosive Charge', 'w': 'Purge', 
                            'e': 'Disdain', 'r': 'Fear Beyond Death'}, 
            'Varus':     {'p': 'Living Vengeance', 'q': 'Piercing Arrow', 'w': 'Blighted Quiver', 
                            'e': 'Hail of Arrows', 'r': 'Chain of Corruption'}, 
            'Vayne':     {'p': 'Night Hunter', 'q': 'Tumble', 'w': 'Silver Bolts', 
                            'e': 'Condemn', 'r': 'Final Hour'},          
            'Veigar':    {'p': 'Phenomenal Evil Power', 'q': 'Baleful Strike', 'w': 'Dark Matter', 
                            'e': 'Event Horizon', 'r': 'Primordial Burst'}, 
            "Vel'Koz":   {'p': 'Organic Deconstruction', 'q': 'Plasma Fission', 'w': 'Void Rift', 
                            'e': 'Tectonic Disruption', 'r': 'Life Form Disintegration Ray'}, 
            'Vi':       {'p': 'Blast Shield', 'q': 'Vault Breaker', 'w': 'Denting Blows', 
                            'e': 'Excessive Force', 'r': 'Assault and Battery'}, 
            'Viktor':    {'p': 'Glorious Evolution', 'q': 'Siphon Power', 'w': 'Gravity Field', 
                            'e': 'Death Ray', 'r': 'Chaos Storm'}, 
            'Vladimir':  {'p': 'Crimson Pact', 'q': 'Transfusion', 'w': 'Sanguine Pool', 
                            'e': 'Tides of Blood', 'r': 'Hemoplague'}, 
            'Volibear':  {'p': 'Chosen of the Storm', 'q': 'Rolling Thunder', 'w': 'Frenzy', 
                            'e': 'Majestic Roar', 'r': 'Thunder Claws'}, 
            'Warwick':   {'p': 'Eternal Hunger', 'q': 'Jaws of the Beast', 'w': 'Blood Hunt', 
                            'e': 'Primal Howl', 'r': 'Infinite Duress'}, 
            'Wukong':    {'p': 'Stone Skin', 'q': 'Crushing Blow', 'w': 'Decoy', 
                            'e': 'Nimbus Strike', 'r': 'Cyclone'},             
            'Xayah':    {'p': 'Clean Cuts', 'q': 'Double Daggers', 'w': 'Deadly Plumage', 
                            'e': 'Bladecaller', 'r': 'Featherstorm'}, 
            'Xerath':    {'p': 'Mana Surge', 'q': 'Arcanopulse', 'w': 'Eye of Destruction', 
                            'e': 'Shocking Orb', 'r': 'Rite of the Arcane'}, 
            'Xin_Zhao':  {'p': 'Determination', 'q': 'Three Talon Strike', 'w': 'Wind Becomes Lightning', 
                            'e': 'Audacious Charge', 'r': 'Crescent Guard'}, 
            'Yasuo':    {'p': 'Way of the Wanderer', 'q': 'Steel Tempest', 'w': 'Wind Wall', 
                            'e': 'Sweeping Blade', 'r': 'Last Breath'}, 
            'Yorick':    {'p': 'Shepherd of Souls', 'q': 'Last Rites', 'alt_q': 'Awakening', 'w': 'Dark Procession', 
                            'e': 'Mourning Mist', 'r': 'Eulogy of the Isles'}, 
            'Zac':      {'p': 'Cell Division', 'q': 'Stretching Strike', 'w': 'Unstable Matter', 
                            'e': 'Elastic Slingshot', 'r': "Let's Bounce!"}, 
            'Zed':      {'p': 'Contempt for the Weak', 'q': 'Razor Shuriken', 'w': 'Living Shadow', 
                            'e': 'Shadow Slash', 'r': 'Death Mark'}, 
            'Ziggs':     {'p': 'Short Fuse', 'q': 'Bouncing Bomb', 'w': 'Satchel Charge', 
                            'e': 'Hexplosive Minefield', 'r': 'Mega Inferno Bomb'}, 
            'Zilean':    {'p': 'Time in a Bottle', 'q': 'Time Bomb', 'w': 'Rewind', 
                            'e': 'Time Warp', 'r': 'Chronoshift'}, 
            'Zoe':      {'p': 'More Sparkles!', 'q': 'Paddle Star', 'w': 'Spell Thief', 
                            'e': 'Sleepy Trouble Bubble', 'r': 'Portal Jump'}, 
            'Zyra':     {'p': 'Garden of Thorns', 'q': 'Deadly Spines', 'w': 'Rampant Growth', 
                            'e': 'Grasping Roots', 'r': 'Stranglethorns'}}

map_ = {'Aatrox': 'aatrox-114', 'Ahri': 'ahri-89', 'Akali': 'akali-50', 'Alistar': 'alistar-4', 
        'Amumu': 'amumu-23', 'Anivia': 'anivia-25', 'Annie': 'annie-1', 'Ashe': 'ashe-13', 'Aurelion_Sol': 'aurelion-sol-130', 
        'Azir': 'azir-121', 'Bard': 'bard-124', 'Blitzcrank': 'blitzcrank-34', 'Brand': 'brand-74', 'Braum': 'braum-119', 
        'Caitlyn': 'caitlyn-67', 'Camille': 'camille-134', 'Cassiopeia': 'cassiopeia-66', "Cho'Gath": 'chogath-22', 
        'Corki': 'corki-31', 'Darius': 'darius-98', 'Diana': 'diana-102', 'Dr._Mundo': 'dr-mundo-26', 'Draven': 'draven-99', 
        'Ekko': 'ekko-125', 'Elise': 'elise-106', 'Evelynn': 'evelynn-19', 'Ezreal': 'ezreal-47', 
        'Fiddlesticks': 'fiddlesticks-38', 'Fiora': 'fiora-94', 'Fizz': 'fizz-87', 'Galio': 'galio-57', 
        'Gangplank': 'gangplank-30', 'Garen': 'garen-51', 'Gnar': 'gnar-120', 'Gragas': 'gragas-45', 'Graves': 'graves-85', 
        'Hecarim': 'hecarim-96', 'Heimerdinger': 'heimerdinger-40', 'Illaoi': 'illaoi-128', 'Irelia': 'irelia-64', 
        'Ivern': 'ivern-133', 'Janna': 'janna-29', 'Jarvan_IV': 'jarvan-iv-71', 'Jax': 'jax-15', 'Jayce': 'jayce-100', 
        'Jhin': 'jhin-129', 'Jinx': 'jinx-116', "Kai'Sa": 'kaisa-145', 'Kalista': 'kalista-122', 'Karma': 'karma-69', 
        'Karthus': 'karthus-21', 'Kassadin': 'kassadin-27', 'Katarina': 'katarina-36', 'Kayle': 'kayle-2', 
        'Kayn': 'kayn-137', 'Kennen': 'kennen-49', "Kha'Zix": 'khazix-105', 'Kindred': 'kindred-127', 'Kled': 'kled-132', 
        "Kog'Maw": 'kogmaw-54', 'LeBlanc': 'leblanc-63', 'Lee_Sin': 'lee-sin-73', 'Leona': 'leona-79', 
        'Lissandra': 'lissandra-113', 'Lucian': 'lucian-115', 'Lulu': 'lulu-95', 'Lux': 'lux-62', 'Malphite': 'malphite-35', 
        'Malzahar': 'malzahar-52', 'Maokai': 'maokai-70', 'Master_Yi': 'master-yi-3', 'Miss_Fortune': 'miss-fortune-59', 
        'Mordekaiser': 'mordekaiser-46', 'Morgana': 'morgana-16', 'Nami': 'nami-108', 'Nasus': 'nasus-37', 
        'Nautilus': 'nautilus-93', 'Nidalee': 'nidalee-42', 'Nocturne': 'nocturne-72', 'Nunu': 'nunu-12', 'Olaf': 'olaf-53', 
        'Orianna': 'orianna-77', 'Ornn': 'ornn-139', 'Pantheon': 'pantheon-44', 'Poppy': 'poppy-43', 'Pyke': 'pyke-141', 'Quinn': 'quinn-111', 
        'Rakan': 'rakan-136', 'Rammus': 'rammus-24', "Rek'Sai": 'reksai-123', 'Renekton': 'renekton-68', 
        'Rengar': 'rengar-103', 'Riven': 'riven-83', 'Rumble': 'rumble-75', 'Ryze': 'ryze-5', 'Sejuani': 'sejuani-91', 
        'Shaco': 'shaco-41', 'Shen': 'shen-48', 'Shyvana': 'shyvana-86', 'Singed': 'singed-18', 'Sion': 'sion-6', 
        'Sivir': 'sivir-7', 'Skarner': 'skarner-81', 'Sona': 'sona-60', 'Soraka': 'soraka-8', 'Swain': 'swain-61', 
        'Syndra': 'syndra-104', 'Tahm_Kench': 'tahm-kench-126', 'Taliyah': 'taliyah-131', 'Talon': 'talon-82', 
        'Taric': 'taric-32', 'Teemo': 'teemo-9', 'Thresh': 'thresh-110', 'Tristana': 'tristana-10', 'Trundle': 'trundle-65', 
        'Tryndamere': 'tryndamere-14', 'Twisted_Fate': 'twisted-fate-28', 'Twitch': 'twitch-20', 'Udyr': 'udyr-39', 
        'Urgot': 'urgot-58', 'Varus': 'varus-97', 'Vayne': 'vayne-76', 'Veigar': 'veigar-33', "Vel'Koz": 'velkoz-118', 
        'Vi': 'vi-109', 'Viktor': 'viktor-90', 'Vladimir': 'vladimir-56', 'Volibear': 'volibear-88', 
        'Warwick': 'warwick-11', 'Wukong': 'wukong-80', 'Xayah': 'xayah-135', 'Xerath': 'xerath-84', 
        'Xin_Zhao': 'xin-zhao-55', 'Yasuo': 'yasuo-117', 'Yorick': 'yorick-78', 'Zac': 'zac-112', 'Zed': 'zed-107', 
        'Ziggs': 'ziggs-92', 'Zilean': 'zilean-17', 'Zoe': 'zoe-140', 'Zyra': 'zyra-101'}

pyke = {'Pyke':     {'p': 'Gift of the Drowned Ones', 'q': 'Bone Skewer', 'w': 'Ghostwater Dive', 
                    'e': 'Phantom Undertow', 'r': "Death from Below"}}



